Lesson14 fercan
frontend-from-0/181223-exercises pull request #30
Opened 2024-04-21 18:36 UTC by fers9021

2024-04-21 18:58 UTC, fers9021 commented
last one

2024-04-21 19:48 UTC, annasvst requested changes

2024-04-21 19:48 UTC, annasvst commented on Lesson14/fercan/script.js
> +number7 = '++number6' ;
You need to declare a variable number7. Proper way of doing it is to use either 'let' or 'const' keyword in the name of the variable.
Sice we want to set number7 to number6 + 1, don't use quotes around `++number6`.
```suggestion
const number7 = ++number6;
```

2024-04-21 19:48 UTC, annasvst commented on Lesson14/fercan/script.js
> +console.log('Exercise 9:, ${number7}');
```suggestion
console.log('Exercise 9:, ${number6}, ${number7}');
```

2024-04-21 19:48 UTC, annasvst commented on Lesson14/fercan/script.js
> +number9 = 'number8++';
```suggestion
const number9 = number8++;
```

2024-04-21 19:48 UTC, annasvst commented on Lesson14/fercan/script.js
> +console.log('number10');
This console.log does not log the value of `number10` variable but only logs a string 'number10' (which is not really related to the `number10` variable).
```suggestion
console.log('Ex. 11: number10 is', number10);
```

2024-04-21 19:48 UTC, annasvst commented on Lesson14/fercan/script.js
> +console.log('newResult');
```suggestion
console.log('Ex.2 newResult:', newResult);  
```

2024-06-12 21:41 UTC, fers9021 reviewed
ok

2024-06-12 21:44 UTC, fers9021 reviewed
ok

2024-06-12 21:44 UTC, fers9021 reviewed
ok

2024-06-12 21:45 UTC, fers9021 reviewed
ok

2024-06-12 21:45 UTC, fers9021 reviewed
ok

2024-06-12 21:46 UTC, fers9021 reviewed
ok

2024-06-12 21:47 UTC, fers9021 reviewed
ok

2024-06-12 21:48 UTC, fers9021 reviewed
ok

2024-06-12 22:09 UTC, annasvst approved these changes
Looks good, approved ✅

2024-06-12 22:21 UTC, merged