first
frontend-from-0/181223-exercises pull request #51
Opened 2024-05-07 20:14 UTC by fers9021

2024-05-12 21:33 UTC, fers9021 commented
finished

2024-05-13 11:35 UTC, annasvst requested changes
Added comment fro lesson 16

2024-05-13 11:35 UTC, annasvst commented on Lesson16/fercan/script.js
> +// 3. Write a function that asks the user to enter two numbers and checks if the first number is greater than, less than, or equal to the second number using if else statement.
In this exercise, you're asked to write a function, so you need to start with a function definition, e.g.:
```

function compareNumbers(number1, number2) {
// if statement should be here inside the function
}
```

In our case, 'asks the user to enter two numbers' means that the function should take 2 parameters (number1, number2) as added in the example above. 

After function definition is created, it's time to call the function with actual numbers:
```
compareNumbers(2, 10);
compareNumbers(-20, 0);
compareNumbers(23, 3);

```

2024-05-13 11:35 UTC, annasvst commented on Lesson16/fercan/script.js
> +function isLeapYear (year) {
The function does not work correctly now as if you use 'else' statement, you cannot provide a condition. https://www.w3schools.com/js/js_if_else.asp

You could do like this:
```
if(year%4==0 && year%100!=0){
        console.log('It\'s a leap year');
     } else if (year%400==0); {  
        console.log('It\'s a leap year');
    } else {
      console.log('It\'s not a leap year');
  }
}
```

or you can do it in a shorter way by combining 2 conditions with logical OR statement (||):
```
if ((year % 4 === 0 && year % 100 !== 0) || year % 400 === 0) {
        return `${year} is leap year`;
    } else {
        return `${year} is not a leap year`;
    }
```

2024-05-13 11:35 UTC, annasvst commented on Lesson16/fercan/script.js
> +let grade=0;
Here function definition is missing, try to write the code similar to the first example

2024-05-13 11:35 UTC, annasvst commented on Lesson16/fercan/script.js
> +
Add some function calls below the function definition, e.g. 

```
testFailOrPass(40);
testFailOrPass(70);
testFailOrPass(99);

```

2024-05-13 11:42 UTC, annasvst requested changes

2024-05-13 11:42 UTC, annasvst commented on Lesson17/fercan/script.js
> +for(let i=1; i<=10; i++){
We need to print numbers till 20, so `i<=20`

2024-05-13 11:42 UTC, annasvst commented on Lesson17/fercan/script.js
> +console.log('answer to number6: no answer - - - - - - - - - - - - ');
I think we did this exercises in the lesson, feel free to look in the lesson notes

2024-06-15 06:04 UTC, fers9021 reviewed
fixed

2024-06-18 19:17 UTC, annasvst approved these changes
Approved

2024-06-18 19:27 UTC, merged