Gokhan Lesson 23
frontend-from-0/181223-exercises pull request #85
Opened 2024-07-03 19:41 UTC by G-Memis

2024-07-15 16:35 UTC, annasvst requested changes
Hi Gökhan, all good code wise (I left minor comments for the future). However, I'd like you to correct the folder name. Folder should be named exactly 'Lesson23' and then there should be folder 'gokhan' inside of it. There you can place html, css and js files. :) 

After you move the files, you should be able to commit and push again. If you have problems, let me know.

2024-07-15 16:35 UTC, annasvst commented on Lesson 23 Gokhan/styles.css
> +    margin: 0;
It's usually not good (and not efficient) to remove margin and padding from all elements at once. Better to remove margin and padding selectively from elements that really don't need it (e.g. body, ul, ol, etc.)

2024-07-15 16:35 UTC, annasvst commented on Lesson 23 Gokhan/styles.css
> +    padding: 3rem;
If you want to use rem, make sure that you set font-size explicitly on the body / html/ root element.

2024-07-16 21:03 UTC, G-Memis commented on Lesson 23 Gokhan/styles.css
> +    padding: 3rem;
i changed it with 20px :)

2024-07-17 09:58 UTC, annasvst approved these changes

2024-07-18 19:06 UTC, merged